# Stefan Haug 2020
# Institute of Genetic Epidemiology
# University Hospital Freiburg
# stefan.haug@uniklinik-freiburg.de
# Include: Copyright (c) 2020 Roman Hillje


##----------------------------------------------------------------------------##
# Extract data from Seurat file which is relevant for NephGen scExplorer
# data is stored in a list (containing different formats) and then
# exported to an rds file.
# species, number of clusters, number of cells are added to the filename?
##----------------------------------------------------------------------------##

# Preparation of Seurat file (for Version >= 3):

# 1) EXPRESSION: log-normalized expression should be in object@assays[[assay]]@data
#    assay default value is "RNA".

# 2) CLUSTER NAMES: Should be in object@meta.data[[column_cluster]]
#    column_cluster must be entered.

# 3) SAMPLE NAMES (not needed currently) should be in object@meta.data[[column_sample]]
#    column_sample must be entered.

# 4) nUMI: Should be in object@meta.data[[column_nUMI]]
#    column_nUMI must be entered.

# 5) GENE NAMES: Should be in object@meta.data[[column_nGene]]
#    column_nGene must be entered.

# 6) DIMENSIONAL REDUCTIONS should be in object@reductions$reduction_name@cell.embeddings
#    reduction_name = umap, tSNA or other. If no dim-reduction available, 
#    the first 2 components of the pca are exported.

# 7) MARKER GENES: should be in object@misc$marker_genes$by_cluster with the following 7 column names:
#    "p_val", "avg_logFC", "pct.1", "pct.2", "p_val_adj", "cluster", "gene"
#    in arbitrary order. These are the column names from the table generated by the
#    findAllMarkers Function in Seurat V 3.


# OUTPUT List (RDS-file) contains:

# sample_data()$experiment (information about experiment (dataset))
# sample_data()$cluster_names (list with cluster names)
# sample_data()$sample_names (list with sample names)
# sample_data()$cells (dataframe with various parameters ==> needed are "$cluster" and  "$cell_barcode")
# sample_data()$marker_genes (data frame with marker genes by cluster)
# sample_data()$projections (List with dataframes one for each projection)
# sample_data()$expression  (dcgMatrix with expression data)

exportFromSeurat <- function(
  object,
  assay = 'RNA',
  file,
  experiment_name,
  organism,
  column_sample = 'sample',
  column_cluster = 'cluster',
  column_nUMI = 'nUMI',
  column_nGene = 'nGene',
  column_cell_cycle_seurat = NULL,
  column_cell_cycle_cyclone = NULL,
  add_all_meta_data = FALSE
) {
  
  ## check if Seurat is installed
  if (!requireNamespace("Seurat", quietly = TRUE))
  {
    stop(
      "Package 'Seurat' needed for this function to work. Please install it.",
      call. = FALSE
    )
  }
  ##--------------------------------------------------------------------------##
  ## check provided parameters (no changes to cerebro)
  ##--------------------------------------------------------------------------##
  
  # `column_sample`
  if ( (column_sample %in% names(object@meta.data) == FALSE ) )
  {
    stop(
      'Column specified in `column_sample` not found in meta data.',
      call. = FALSE
    )
  }
  
  ## `column_cluster`
  if ( (column_cluster %in% names(object@meta.data) == FALSE ) )
  {
    stop(
      'Column specified in `column_cluster` not found in meta data.',
      call. = FALSE
    )
  }
  ## `column_nUMI`
  if ( (column_nUMI %in% names(object@meta.data) == FALSE ) )
  {
    stop(
      paste0(
        'Column with number of transcripts per cell (`nUMI`) not found in ',
        'meta data.'
      ),
      call. = FALSE
    )
  }
  ## `column_nGene`
  if ( (column_nGene %in% names(object@meta.data) == FALSE ) )
  {
    stop(
      paste0(
        'Column with number of expressed genes per cell (`nGene`) not found ',
        'in meta data.'
      ),
      call. = FALSE
    )
  }
  
  ##--------------------------------------------------------------------------##
  ## initialize export list (no changes to cerebro)
  ##--------------------------------------------------------------------------##
  message(
    paste0(
      '[', format(Sys.time(), '%H:%M:%S'), '] Initializing Cerebro object...'
    )
  )
  export <- list(
    experiment = list(
      experiment_name = experiment_name,
      organism = organism
    )
  )
  
  ##--------------------------------------------------------------------------##
  ## collect some more data if present (excluded)
  ##--------------------------------------------------------------------------##
  
  
  ##--------------------------------------------------------------------------##
  ## get sample names (now exported, currently not used in scExplorer)
  ##--------------------------------------------------------------------------##
  if ( is.factor(object@meta.data[[column_sample]]) )
  {
    export$sample_names <- levels(object@meta.data[[column_sample]])
  } else
  {
    export$sample_names <- unique(object@meta.data[[column_sample]])
  }
  
  
  ##--------------------------------------------------------------------------##
  ## get cluster names (now also exported directly)
  ##--------------------------------------------------------------------------##
  if ( is.factor(object@meta.data[[column_cluster]]) )
  {
    export$cluster_names <- levels(object@meta.data[[column_cluster]])
  } else
  {
    export$cluster_names <- unique(object@meta.data[[column_cluster]]) %>% sort()
  }
  
  ##--------------------------------------------------------------------------##
  ## meta data
  ##--------------------------------------------------------------------------##
  message(
    paste0(
      '[', format(Sys.time(), '%H:%M:%S'), '] Collecting available meta data...'
    )
  )
  meta_data_columns <- names(object@meta.data)
  export$cells <- data.frame(
    'sample' = factor(
      object@meta.data[[column_sample]], levels = c(export$sample_names)
    ),
    'cluster' = factor(
      object@meta.data[[column_cluster]], levels = c(export$cluster_names)
    ),
    'nUMI' = object@meta.data[[column_nUMI]],
    'nGene' = object@meta.data[[column_nGene]]
  )
  meta_data_columns <- meta_data_columns[-which(meta_data_columns == column_sample)]
  meta_data_columns <- meta_data_columns[-which(meta_data_columns == column_cluster)]
  meta_data_columns <- meta_data_columns[-which(meta_data_columns == column_nUMI)]
  meta_data_columns <- meta_data_columns[-which(meta_data_columns == column_nGene)]
  ##--------------------------------------------------------------------------##
  ## cell barcode
  ##--------------------------------------------------------------------------##
  if ( !is.null(rownames(as.data.frame(object@meta.data))) )
  {
    export$cells$cell_barcode <- rownames(as.data.frame(object@meta.data))
  }
  
  
  ##--------------------------------------------------------------------------##
  ## add all other meta data if specified (no changes to cerebro)
  ##--------------------------------------------------------------------------##
  if ( add_all_meta_data )
  {
    message(
      paste0(
        '[', format(Sys.time(), '%H:%M:%S'),
        '] Extracting all meta data columns...'
      )
    )
    export$cells <- cbind(export$cells, object@meta.data[meta_data_columns])
  }
  
  
  ##--------------------------------------------------------------------------##
  ## most expressed genes (excluded)
  ##--------------------------------------------------------------------------##
  
  
  ##--------------------------------------------------------------------------##
  ## marker genes (new: renaming of columns)
  ##--------------------------------------------------------------------------##
  if ( !is.null(object@misc$marker_genes) )
  {
    message(
      paste0(
        '[', format(Sys.time(), '%H:%M:%S'),
        '] Extracting tables of marker genes...'
      )
    )
    
    export$marker_genes <- object@misc$marker_genes[c("gene", 
                                                     "p_val", 
                                                     "p_val_adj",
                                                     "avg_logFC",
                                                     "pct.1",
                                                     "pct.2",
                                                     "cluster")]
    
    colnames(export$marker_genes) <- c("Gene", 
                                       "p Value", 
                                       "p Value adjusted",
                                       "log Fold Change",
                                       "% Cells in Cluster Expressing Gene",
                                       "% cells in All Other Clusters Expressing Gene", 
                                       "Cluster")
  }
  
  
  ##--------------------------------------------------------------------------##
  ## enriched pathways excluded
  ##--------------------------------------------------------------------------##
  
  
  ##--------------------------------------------------------------------------##
  ## dimensional reductions (no changes to cerebro)
  ##--------------------------------------------------------------------------##
  message(
    paste0(
      '[', format(Sys.time(), '%H:%M:%S'),
      '] Extracting dimensional reductions...'
    )
  )
  export$projections <- list()
  if ( object@version < 3 )
  {
    projections_available <- names(object@dr)
    projections_available_pca <- projections_available[grep(
      projections_available, pattern = 'pca', ignore.case = TRUE, invert = FALSE
    )]
    projections_available_non_pca <- projections_available[grep(
      projections_available, pattern = 'pca', ignore.case = TRUE, invert = TRUE
    )]
    if ( length(projections_available) == 0 )
    {
      stop('No dimensional reductions available.', call. = FALSE)
    } else if (
      length(projections_available) == 1 &&
      length(projections_available_pca) == 1 )
    {
      warning(
        paste0(
          'Warning: Only PCA as dimensional reduction found, will export ',
          'first and second principal components. Consider using tSNE and/or ',
          'UMAP instead.'
        )
      )
      export$projections[[projections_available]] <- as.data.frame(
        object@dr[[projections_available]]@cell.embeddings
      )
    } else if ( length(projections_available_non_pca) > 0 )
    {
      message(
        paste0(
          '[', format(Sys.time(), '%H:%M:%S'), '] ',
          'Will export the following dimensional reductions: ',
          paste(projections_available_non_pca, collapse = ', ')
        )
      )
      for ( i in projections_available_non_pca )
      {
        export$projections[[i]] <- as.data.frame(object@dr[[i]]@cell.embeddings)
      }
    }
  } else
  {
    projections_available <- names(object@reductions)
    projections_available_pca <- projections_available[grep(
      projections_available, pattern = 'pca', ignore.case = TRUE, invert = FALSE
    )]
    projections_available_non_pca <- projections_available[grep(
      projections_available, pattern = 'pca', ignore.case = TRUE, invert = TRUE
    )]
    if ( length(projections_available) == 0 )
    {
      stop('No dimensional reductions available.', call. = FALSE)
    } else if (
      length(projections_available) == 1 &&
      length(projections_available_pca) == 1 )
    {
      export$projections[[projections_available]] <- as.data.frame(
        object@reductions[[projections_available]]@cell.embeddings
      )
      warning(
        paste0(
          'Warning: Only PCA as dimensional reduction found, will export ',
          'first and second principal components. Consider using tSNE and/or ',
          'UMAP instead.'
        )
      )
    } else if ( length(projections_available_non_pca) >= 1 )
    {
      message(
        paste0(
          '[', format(Sys.time(), '%H:%M:%S'), '] ',
          'Will export the following dimensional reductions: ',
          paste(projections_available_non_pca, collapse = ', ')
        )
      )
      for ( i in projections_available_non_pca )
      {
        export$projections[[i]] <- as.data.frame(
          object@reductions[[i]]@cell.embeddings
        )
      }
    }
  }
  
  
  ##--------------------------------------------------------------------------##
  ## trajectories (excluded)
  ##--------------------------------------------------------------------------##
  
  
  ##--------------------------------------------------------------------------##
  ## cluster tree (excluded)
  ##--------------------------------------------------------------------------##
  
  
  ##--------------------------------------------------------------------------##
  ## log-normalized expression (no changes to cerebro)
  ##--------------------------------------------------------------------------##
  message(
    paste0(
      '[', format(Sys.time(), '%H:%M:%S'),
      '] Extracting log-normalized expression data...'
    )
  )
  if ( object@version < 3 )
  {
    ## check if `data` matrix exist in provided Seurat object
    if ( is.null(object@data) )
    {
      stop(
        paste0(
          '`data` matrix could not be found in provided Seurat ',
          'object.'
        ),
        call. = FALSE
      )
    }
    export$expression <- object@data
  } else
  {
    ## check if provided assay exists
    if ( (assay %in% names(object@assays) == FALSE ) )
    {
      stop(
        paste0(
          'Assay slot `', assay, '` could not be found in provided Seurat ',
          'object.'
        ),
        call. = FALSE
      )
    }
    ## check if `data` matrix exist in provided assay
    if ( is.null(object@assays[[assay]]@data) )
    {
      stop(
        paste0(
          '`data` matrix could not be found in `', assay, '` assay slot.'
        ),
        call. = FALSE
      )
    }
    export$expression <- object@assays[[assay]]@data
  }
  
  
  ##--------------------------------------------------------------------------##
  ## save export object to disk (no changes to cerebro)
  ##--------------------------------------------------------------------------##
  if ( !file.exists(dirname(file)) )
  {
    message(
      paste0(
        '[', format(Sys.time(), '%H:%M:%S'),
        '] Creating output directory...'
      )
    )
    dir.create(dirname(file), showWarnings = FALSE)
  }
  message(
    paste0(
      '[', format(Sys.time(), '%H:%M:%S'), '] Saving scExplorer file...'
    )
  )
  saveRDS(export, file)
}